name: linter

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install PHP Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install JavaScript Dependencies
        run: bun install --quiet --frozen-lockfile

      - name: Format backend
        run: composer run -- format:check

      - name: Format Frontend
        run: bun run --bun -- format:check

      - name: Lint Frontend
        run: bun run --bun -- lint:check
